[build]
  command = "npm install && npm run client-install && npm run client-build"
  publish = "client/build"

[build.environment]
  MONGODB_URI = "mongodb+srv://user:codeforinterview@job-portal.4zinb.mongodb.net/"
  NODE_ENV = "production"
  FRONTEND_URL = "https://job-portal-by-arnav.netlify.app"

[build.processing]
  publish = "client/build"

[context.production.environment]
  REACT_APP_API_BASE_URL = "http://localhost:8000/api"

[[plugins]]
  package = "@netlify/plugin-functions-core"

